"""add_domain_filter

Revision ID: 74fe1ff71c46
Revises: 7596b28fa416
Create Date: 2025-11-22 16:00:38.902535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74fe1ff71c46'
down_revision: Union[str, None] = '7596b28fa416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_accounts', sa.Column('domain_filter', sa.Text(), nullable=True))
    op.alter_column('email_accounts', 'smtp_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('email_accounts', 'smtp_password_encrypted',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_accounts', 'smtp_password_encrypted',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('email_accounts', 'smtp_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('email_accounts', 'domain_filter')
    # ### end Alembic commands ###
